name = "kivo-api"
compatibility_date = "2024-01-01"

main = "src/worker.js"


[[d1_databases]]
binding = "DB"
database_name = "kivo-db"
database_id = "cb20c7c0-f99e-46ec-bd87-d223940860be"

[ai]
binding = "AI"
